---
title: "distribution_parasites_per_ind"
output: html_notebook
---

```{r setup, echo=FALSE}
# Knitr settings: 
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
options(scipen = 999)
```

```{r, echo=FALSE}
source("./src/wgs-mining-validation-source.R")
```

```{r}
df <- read.csv(file.path(data_path, "wrangled", "full_data.csv"))
sample_info <- read.csv(file.path(data_path, "sample-info", "df-migrant-miseq.csv"))

```

```{r}
df_wgs <- df %>%
  filter(method == "WGS mining") %>%
  group_by(ID, method) %>% 
  tally()

df_meta <- df %>%
  filter(method == "Metabarcoding") %>%
  group_by(ID, method) %>% 
  tally()

df_meta_kraken <- df %>%
  filter(method == "Metabarcoding Kraken") %>%
  group_by(ID, method) %>% 
  tally()
```

```{r}
df_0_wgs_mining <- sample_info %>%
  dplyr::filter(ID %!in% df_wgs$ID) %>%
  select(ID) %>%
  mutate(method = "WGS mining", n = 0)

df_0_metabarcoding <- sample_info %>%
  filter(ID %!in% df_meta$ID) %>%
  select(ID) %>%
  mutate(method = "Metabarcoding", n = 0)

df_0_metabarcoding_kraken <- sample_info %>%
  filter(ID %!in% df_meta_kraken$ID) %>%
  select(ID) %>%
  mutate(method = "Metabarcoding Kraken", n = 0)

df_plot <- rbind(df_0_wgs_mining, df_0_metabarcoding, df_0_metabarcoding_kraken, df_meta, df_wgs, df_meta_kraken) 
```


```{r}
p1 <- 
  ggplot(df_plot, aes(x = n)) +
            geom_bar(binwidth = 1, position = "dodge", fill = palette[5], color = "black") +
  aes(y = ..count..) +
  facet_wrap( ~ method, ncol =1)+
  scale_x_continuous(name ="Number of parasites detected per individual", breaks = c(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16))+
  ylab("Number of individuals") +
    theme_minimal()

p1
```
```{r}
ggplot2::ggsave(file.path(figures_path, "Figure3.png"), 
                p1,
                width = 10,
                height = 12,
                units = c("cm"))
```


