---
title: "Phyloseq"
output: html_notebook
---

```{r setup, echo=FALSE}
# Knitr settings: 
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
options(scipen = 999)
```

```{r, echo=FALSE}
source("./src/wgs-mining-validation-source.R")
```

```{r}
sample_info <- read.csv(file.path(data_path, "sample-info", "df-migrant-miseq.csv"))
asv_counts <- read.table(file.path(data_path, "metabarcoding", "ASVs_counts.tsv"))
```

create tax table 
```{r}
asv_assigned <- read.csv(file.path(data_path, "metabarcoding", "ASV.report.stats.csv"))
asv_names<- read.csv(file.path(data_path, "metabarcoding", "ASV.report.csv"))

```

```{r}

tax_table <- asv_assigned %>%
  left_join(asv_names, by = c("taxid")) %>%
  dplyr::select(ASV, taxname) %>%
  mutate(genus = case_when(
    grepl("Cryptosporidium", taxname) ~ "Cryptosporidium",
    grepl("Cyclospora", taxname) ~ "Cyclospora",
    grepl("Eimeria", taxname) ~ "Eimeria",
    grepl("Toxoplasma", taxname) ~ "Toxoplasma",
    grepl("Ascogregarina", taxname) ~ "Ascogregarina",
    grepl("Babesia", taxname) ~ "Babesia",
    grepl("Eimeriorina", taxname) ~ "Eimeriorina (suborder)",
    grepl("Conoidasida", taxname) ~ "Conoidasida (class)",
    grepl("Theileria", taxname) ~ "Theileria",
    grepl("Haemoproteus", taxname) ~ "Haemoproteus",

    TRUE ~ NA_character_
  ))
```


format data for phyloseq
```{r}
asv_counts <- as.matrix(asv_counts)

# Assuming your matrix is named 'my_matrix'
# Get the column names
original_colnames <- colnames(asv_counts)

# Use gsub to extract the part of the string that starts with 'B' and is followed by three digits
new_colnames <- gsub(".*(B\\d{3}).*", "\\1", original_colnames)

# Assign the new column names to the matrix
colnames(asv_counts) <- new_colnames

rownames(tax_table) <- tax_table$ASV
#tax_table <- tax_table[,-1]
tax_table <- as.matrix(tax_table)
sample_info <- drop_na(sample_info)
rownames(sample_info) <- sample_info$sample_id_blood
```

```{r}
OTU = otu_table(asv_counts, taxa_are_rows = TRUE)
TAX = tax_table(tax_table)
sample_data <- sample_data(sample_info)
```

```{r}
physeq = phyloseq(OTU, TAX, sample_data)
```

```{r}
api.physeq = subset_taxa(physeq, genus!="NA")

ps.prop <- transform_sample_counts(api.physeq, function(OTU) OTU/sum(OTU))
```

```{r}
pal <- "Set3"
phyloseq::plot_bar(api.physeq, x= "Sample", fill = "genus")+geom_bar(stat="identity")


```

```{r}
phyloseq::plot_bar(api.physeq, x= "Sample", fill = "taxonomy_Genus")#+
  #geom_bar(aes(color = "taxonomy_Division", fill = "taxonomy_Division", stat = "identity", position="stack"))
```