---
title: "conifer-output-formatting"
output: html_notebook
---

```{r setup, echo=FALSE}
# Knitr settings: 
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
options(scipen = 999)
```

```{r, echo=FALSE}
source("./src/wgs-mining-validation-source.R")
```

```{r}
sample_info <- read.csv(file.path(data_path, "sample-info", "df-migrant-miseq.csv"))

asv_counts <- read.table(file.path(data_path, "metabarcoding", "ASVs_counts.tsv"))

df_wgs <- read_delim(file.path(data_path, "wgs-mining", "df_conifer_C90.csv"))

df_slides <- read_csv(file.path(data_path, "slides", "parasite_counts_slides.csv"))

df_metabarcoding <- read.table(file.path(data_path, "metabarcoding", "basta_ncbi_full.tsv"))

df_pcr <- read_csv(file.path(data_path, "pcr", "mock_pcr_results.csv"))

```

need to put all data in long format
```{r}
pcr_long <- pivot_longer(df_pcr, 
                          cols = c(Leucocytozoon, Haemoproteus, Plasmodium), 
                          names_to = "parasite_name", 
                          values_to = "infected") %>%
  mutate(method = "PCR")%>%
  drop_na() %>%
  select(parasite_name, ID, method)
  

```


```{r}
slides_long <- pivot_longer(df_slides, 
                          cols = c(Leucocytozoon, Haemoproteus, Plasmodium, Atoxoplasma), 
                          names_to = "parasite_name", 
                          values_to = "infected") %>%
  mutate(method = "Slides") %>%
  drop_na()%>%
  select(parasite_name, ID, method)

```


```{r}
df_metabarcoding_separated <- separate(df_metabarcoding, V2, into = c("Kingdom", "Phylum", "Class", "Family", "Order", "Genus", "Species"), sep = ";")

parasite_genera_metabarcoding <- c("Theileria", "Babesia", "Isospora", "Blastocystis", "Eimeria")

asv_counts$ASV <- row.names(asv_counts)   
# Get the column names
original_colnames <- colnames(asv_counts)

# Use gsub to extract the part of the string that starts with 'B' and is followed by three digits
new_colnames <- gsub(".*(B\\d{3}).*", "\\1", original_colnames)

# Assign the new column names to the matrix
colnames(asv_counts) <- new_colnames

sample_ids <- sample_info %>%
  select(ID, sample_id_blood)

metabarcoding_long <- df_metabarcoding_separated %>%
rename("V1" = "ASV") %>%
dplyr::select(ASV, Genus) %>%
filter(Genus %in% parasite_genera_metabarcoding) %>%
left_join(asv_counts, by = "ASV") %>%
  pivot_longer(., 
              cols = starts_with("B"), 
              names_to = "sample_id_blood", 
              values_to = "count") %>%
  select(Genus, sample_id_blood, count) %>%
  rename("Genus" = "parasite_name") %>%
  filter(count > 0) %>%
  left_join(sample_ids, ., by = "sample_id_blood") %>%
  drop_na() %>%
  mutate(method = "Metabarcoding") %>%
  select(parasite_name, ID, method)

```

```{r}
wgs_long <- df_wgs %>%
  select(parasite_name, sample_id) %>%
  rename("sample_id" = "ID") %>%
  mutate(method = "WGS mining")
```

```{r}
full_data <- rbind(wgs_long, metabarcoding_long, slides_long, pcr_long)
```

```{r}
P14 = alphabet.colors(14)
swatch(P14)
pal_parasites = alphabet.colors(length(unique(full_data$parasite_name)))


# Plot using ggplot2 with the custom color palette
ggplot(full_data, aes(x = method, fill = parasite_name)) +
  geom_bar(position = "stack") +
  facet_wrap(~ ID) +
  scale_fill_viridis_d() +  
  labs(title = "Parasite Detection per Sample",
       x = "Method", y = "Count") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

print(pal_parasites)  # Print the palette to check the colors

```
```{r}
library(Polychrome)
P14 = alphabet.colors(14)
P14 <- as.vector(P14)


ggplot(full_data, aes(x = method, fill = parasite_name)) +
  geom_bar(position = "stack") +
  scale_fill_manual(values = P14)+  
  labs(title = "Parasite Detection per Sample",
       x = "Method", y = "Count") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

```



```{r}
# Install ggplot2 if not already installed
if (!requireNamespace("ggplot2", quietly = TRUE)) {
  install.packages("ggplot2")
}

# Load the required libraries
library(ggplot2)
library(dplyr)
library(tidyr)

# Load the data
data <- full_data

# Create a unique identifier for each combination of parasite_name and method
data_summary <- data %>%
  group_by(method, parasite_name) %>%
  summarise(num_samples = n_distinct(ID)) %>%
  ungroup()

# Plot the heatmap using ggplot2
ggplot(data_summary, aes(x = parasite_name, y = method, fill = num_samples)) +
  geom_tile(color = "white") +
  scale_fill_viridis_c() +  
  labs(title = "Parasites detected across each method",
       x = "Parasite Type",
       y = "Method",
       fill = "Number of Samples") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


```

