---
title: "wrangling_metabarcoding"
output: html_notebook
---


```{r setup, echo=FALSE}
# Knitr settings: 
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
options(scipen = 999)
```

```{r, echo=FALSE}
source("./src/wgs-mining-validation-source.R")
```

```{r}
sample_info <- read.csv(file.path(data_path, "sample-info", "df-migrant-miseq.csv"))

asv_counts <- read.table(file.path(data_path, "metabarcoding", "ASVs_counts.tsv"))

df_metabarcoding_blast <- read.table(file.path(data_path, "metabarcoding", "basta_ncbi_full.tsv"))
```


```{r}
df_metabarcoding_separated <- separate(df_metabarcoding_blast, V2, into = c("Kingdom", "Phylum", "Class", "Family", "Order", "Genus", "Species"), sep = ";")

parasite_genera_metabarcoding <- c("Theileria", "Babesia", "Isospora", "Blastocystis", "Eimeria")

asv_counts$ASV <- row.names(asv_counts)   
# Get the column names
original_colnames <- colnames(asv_counts)

# Use gsub to extract the part of the string that starts with 'B' and is followed by three digits
new_colnames <- gsub(".*(B\\d{3}).*", "\\1", original_colnames)

# Assign the new column names to the matrix
colnames(asv_counts) <- new_colnames

sample_ids <- sample_info %>%
  select(ID, sample_id_blood)
```

put data in long format
```{r}
df_metabarcoding_wide <- df_metabarcoding_separated %>%
dplyr::rename("ASV" = V1) %>%
dplyr::select(ASV, Genus) %>%
filter(Genus %in% parasite_genera_metabarcoding) %>%
left_join(asv_counts, by = "ASV") %>%
dplyr::select(-ASV) %>%
  group_by(Genus) %>%
  summarise_all(sum) %>%
  dplyr::rename("parasite_name" = Genus) %>%
  column_to_rownames(var = "parasite_name") %>%
  t() %>%
  as.data.frame() %>%
      mutate(sample_id_blood = rownames(.)) %>%
  left_join(sample_ids, ., by = "sample_id_blood")
```

put data in long format
```{r}
df_metabarcoding_long <- df_metabarcoding_wide %>%
  pivot_longer(cols = -c(sample_id_blood, ID), names_to = "parasite", values_to = "count")
```


```{r}
write_csv(df_metabarcoding_wide, file.path(data_path, "wgs-mining", "wrangled", "df_metabarcoding_wide.csv"))
write_csv(df_metabarcoding_long, file.path(data_path, "wgs-mining", "wrangled", "df_metabarcoding_long.csv"))

```

