---
title: "parasite_detected_wgs_mining"
output: html_notebook
---

```{r setup, echo=FALSE}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
options(scipen = 999)
```

```{r, echo=FALSE}
source("./src/wgs-mining-validation-source.R")
```

```{r}
df_unassembled <- read.csv(file.path(data_path, "wgs-mining", "wrangled", "df_unassembled_wgs_mining.csv"))
df_assembled <- read.csv(file.path(data_path, "wgs-mining", "wrangled", "df_assembled_wgs_mining.csv"))
```

```{r}
confidence_thresholds <- seq(0, 90, by = 10) 

combined_plot_assembled <- lapply(confidence_thresholds, function(threshold) {
  df_assembled %>% 
  group_by(parasite_name, transmission_mode, host, confidence) %>% 
  distinct() %>%
  tally() %>%
  drop_na() %>%
    filter(confidence >= threshold) %>%  
    mutate(confidence = threshold)    
}) %>%
  bind_rows() 

```


```{r}
gen_plot <- sample(palette, 73)

ggplot(combined_plot_assembled, aes(x = confidence, y = n, fill = parasite_name)) + 
  geom_bar(position = "stack", stat= "identity") +
    scale_fill_manual(values = gen_plot)
```
repeat for unassembled data
```{r}
combined_plot_unassembled <- lapply(confidence_thresholds, function(threshold) {
  df_unassembled %>% 
  group_by(parasite_name, transmission_mode, host, confidence) %>% 
  distinct() %>%
  tally() %>%
  drop_na() %>%
    filter(confidence >= threshold) %>%  
    mutate(confidence = threshold)    
}) %>%
  bind_rows() 
```

```{r}
ggplot(combined_plot_unassembled, aes(x = confidence, y = n, fill = parasite_name)) + 
  geom_bar(position = "stack", stat= "identity") +
    scale_fill_manual(values = gen_plot)
```


```{r}
palette_transmission <- c(trans_pal, "grey")
palette_host <- c(host_pal, "grey")
```

```{r}
p_trans_mode_unassembled <- ggplot(combined_plot_unassembled, aes(x = confidence, y = n, fill = transmission_mode)) + 
  geom_bar(position = "stack", stat = "identity", alpha = 0.8) +
  scale_fill_manual(values = palette_transmission, 
                    breaks = c("direct", "flying_insect", "tick_borne", "two_host", "unknown"), 
                    labels = c("Direct", "Flying insect", "Tick", "Two-host", "Unknown")) +
  scale_x_discrete(limits = c(0, 10, 20, 30, 40, 50, 60, 70, 80, 90), 
                   labels = c(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)) +
  labs(title = "C) Paired-end", x = NULL, y = "Detected across samples", fill = "Transmission mode") +
  theme_classic() +
  theme(
    legend.position = "right", 
    text = element_text(size = 15),
        plot.title = element_text(hjust = 0)
  )

p_host_unassembled <- ggplot(combined_plot_unassembled, aes(x = confidence, y = n, fill = host)) + 
  geom_bar(position = "stack", stat = "identity", alpha = 0.8) +
  scale_fill_manual(values = palette_host, 
                    breaks = c("birds", "plants", "invertebrates", "vertebrates", "unknown"), 
                    labels = c("Birds", "Plants", "Invertebrates", "Vertebrates", "Unknown")) +
  scale_x_discrete(limits = c(0, 10, 20, 30, 40, 50, 60, 70, 80, 90), 
                   labels = c(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)) +
  labs(title = "A) Paired-end", x = "Detected across samples", y = NULL, fill = "Recorded host") +
  theme_classic() +
  theme(
    legend.position = "right", 
    text = element_text(size = 15),
        plot.title = element_text(hjust = 0)
  )

p_trans_mode_assembled <- ggplot(combined_plot_assembled, aes(x = confidence, y = n, fill = transmission_mode)) + 
  geom_bar(position = "stack", stat = "identity", alpha = 0.8) +
  scale_fill_manual(values = palette_transmission, 
                    breaks = c("direct", "flying_insect", "tick_borne", "two_host", "unknown"), 
                    labels = c("Direct", "Flying insect", "Tick", "Two-host", "Unknown")) +
  scale_x_discrete(limits = c(0, 10, 20, 30, 40, 50, 60, 70, 80, 90), 
                   labels = c(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)) +
  labs(title = "D) Assembled", x = NULL, y = "Detected across samples", fill = "Transmission mode") +
  theme_classic() +
  theme(
    legend.position = "right", 
    text = element_text(size = 15),
        plot.title = element_text(hjust = 0)
  )

p_host_assembled <- ggplot(combined_plot_assembled, aes(x = confidence, y = n, fill = host)) + 
  geom_bar(position = "stack", stat = "identity", alpha = 0.8) +
  scale_fill_manual(values = palette_host, 
                    breaks = c("birds", "plants", "invertebrates", "vertebrates", "unknown"), 
                    labels = c("Birds", "Plants", "Invertebrates", "Vertebrates", "Unknown")) +
  scale_x_discrete(limits = c(0, 10, 20, 30, 40, 50, 60, 70, 80, 90), 
                   labels = c(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)) +
  labs(title = "B) Assembled", x = "Detected across sample", y = NULL, fill = "Recorded host") +
  theme_classic() +
  theme(
    legend.position = "right", 
    text = element_text(size = 15),
    plot.title = element_text(hjust = 0)
  )

p1_combined_plot_unassembled <- (p_trans_mode_unassembled + p_trans_mode_assembled) + 
  plot_layout(guides = "collect") & 
  theme(
    legend.position = "right",  
    legend.title = element_text(size = 12), 
    legend.text = element_text(size = 10),  
    plot.title = element_text(size = 16, face = "bold", hjust = 0.5),  
    plot.margin = margin(10, 10, 20, 10),  
    text = element_text(size = 15)  
  )

p2_combined_plot_assembled <-  (p_host_unassembled + p_host_assembled) + 
  plot_layout(guides = "collect") & 
  theme(
    legend.position = "right",  
    legend.title = element_text(size = 12),  
    legend.text = element_text(size = 10),  
    plot.title = element_text(size = 16, face = "bold", hjust = 0.5),  
    plot.margin = margin(10, 10, 20, 10), 
    text = element_text(size = 15)  
  )

combined_plot <- (p2_combined_plot_assembled / p1_combined_plot_unassembled) +
  plot_layout(nrow =2) & 
  theme(
    legend.position = "right",  
    legend.title = element_text(size = 12),  
    legend.text = element_text(size = 10),   
    plot.title = element_text(size = 16, face = "bold", hjust = 0.5), 
    plot.margin = margin(10, 10, 20, 10),  
    text = element_text(size = 15)  
  )

combined_plot <- combined_plot + 
  theme(
    plot.title = element_text(size = 18, face = "bold", hjust = 0.5, margin = margin(b = 10)),  
    axis.title.x = element_text(size = 15, vjust = -1, margin = margin(t = 10)),  
    axis.title.y = element_text(size = 15, vjust = 1, margin = margin(r = 10)) 
  )

print(combined_plot)
```


```{r}
ggplot2::ggsave(file.path(figures_path, "kraken_confidence_by_category.png"), 
                combined_plot,
                width = 22,
                height = 20,
                units = c("cm"))

```


